### ISSUE TITLE
highcharts  has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by netchose** [vincentchoqueuse/drum_machine#1]
hello,

Mixed Content: The page at 'https://vincentchoqueuse.github.io/drum_machine/' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/highcharts.js'. This request has been blocked; 

ta juste à mettre un s après le http et ca devrait être bon.

thanks a lot

**Comment by vincentchoqueuse** [comment]
Merci ;)
